Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.box_check_update = false

  config.vm.define "saal-kurS" do |server|
    server.vm.hostname = "saal-kurS"

    server.vm.network "private_network",
      ip: "192.168.56.110"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.provider "libvirt" do |lv|
    lv.memory = 512
    lv.cpus = 1
  end

    server.vm.provision "shell", path: "scripts/install.sh"
  end
end